# Generated by Django 3.2.4 on 2022-06-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_rodro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='rodro',
            new_name='rodo',
        ),
    ]
